# Generated by Django 5.2.1 on 2025-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uc',
            name='id',
        ),
        migrations.AlterField(
            model_name='uc',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
